version: '3.8'

services:
  database:
    container_name: postgres
    image: postgres:15.2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./backend/src/database/db/:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    stop_signal: SIGTERM
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/user_images:/src/user_images
      - ./.env:/src/.env # Можно так делать прокидывать файл переменных окружения в контейнер через volume?
    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./backend/user_images:/usr/share/nginx/html/user_images
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
