FROM python:3.12.3-alpine3.20

WORKDIR /src

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY /src .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
